package ru.yandex.practicum.dto.order;

public enum OrderState {
    NEW, ON_PAYMENT, PAID, ASSEMBLED, ON_DELIVERY, DELIVERED, COMPLETED, DELIVERY_FAILED, ASSEMBLY_FAILED,
    PAYMENT_FAILED, PRODUCT_RETURNED, CANCELED
}
