CREATE TABLE IF NOT EXISTS addresses (
  address_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  country VARCHAR(100),
  city VARCHAR(100),
  street VARCHAR,
  house VARCHAR (10),
  flat VARCHAR (10)
);

CREATE TABLE IF NOT EXISTS orders (
  order_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  shopping_cart_id UUID,
  user_name VARCHAR(50),
  payment_id UUID,
  delivery_id UUID,
  state VARCHAR(50),
  delivery_weight NUMERIC(11, 2),
  delivery_volume NUMERIC(11, 2),
  fragile BOOLEAN,
  total_price NUMERIC(11, 2),
  delivery_price NUMERIC(11, 2),
  product_price NUMERIC(11, 2),
  from_address BIGINT REFERENCES addresses(address_id) ON DELETE RESTRICT NOT NULL,
  to_address BIGINT REFERENCES addresses(address_id) ON DELETE RESTRICT NOT NULL
);

CREATE TABLE IF NOT EXISTS products (
  product_id UUID,
  quantity BIGINT,
  order_id UUID REFERENCES orders(order_id) ON DELETE CASCADE,
  PRIMARY KEY (product_id, order_id)
);
