CREATE TABLE IF NOT EXISTS addresses (
  address_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  country VARCHAR(100),
  city VARCHAR(100),
  street VARCHAR,
  house VARCHAR (10),
  flat VARCHAR (10)
);

CREATE TABLE IF NOT EXISTS deliveries (
  delivery_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  from_address BIGINT REFERENCES addresses(address_id) ON DELETE RESTRICT NOT NULL,
  to_address BIGINT REFERENCES addresses(address_id) ON DELETE RESTRICT NOT NULL,
  order_id UUID NOT NULL,
  delivery_weight NUMERIC(11, 2) NOT NULL,
  delivery_volume NUMERIC(11, 2) NOT NULL,
  fragile BOOLEAN,
  delivery_state VARCHAR(50)
);